<?php

/**
 * Shorthill
 *
 * @copyright   Copyright (c) 2011 Shorthill Solutions (http://www.shorthillsolutions.com)
 * @author      Carlos Ayala <carlos.ayala@shorthillsolutions.com>
 */
?>
<hr>
<footer>
    <p class="pull-left">&copy; <a href="http://dtz.local" target="_blank">DTZ</a> 2013</p>
    <p class="pull-right">Powered by: <a href="http://www.shorthillsolutions.com">www.shorthillsolutions.com</a></p>
</footer>