<?php

/**
 * Shorthill
 *
 * @copyright   Copyright (c) 2013 Shorthill Solutions (http://www.shorthillsolutions.com)
 * @author      Carlos Ayala <carlos.ayala@shorthillsolutions.com>
 */
?>
<div class="navbar">
    <div class="navbar-inner">
        <div class="container-fluid">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                </a>
                <!-- logo del sitio -->
                <a class="brand" href="/admin/index" style="width:300px"> 
                   
                    <span>Comparaclick</span>
                </a>
                <div></div>
                <div class="btn-group pull-left" >
                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="icon-list-alt"></i><span class="hidden-phone"> Menu </span>
                                <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a  href="/admin/index">
                                    <i class="icon-home"> </i>
                                    <span class="hidden-tablet">Home</span>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li><a  href="/admin/ordenes">
                                    <i class="icon-th-list"></i>
                                    <span class="hidden-tablet">Ordenes</span>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li><a  href="/admin/proveedor">
                                    <i class="icon-th-list"></i>
                                    <span class="hidden-tablet">Proveedores/Planes</span>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <li><a  href="/admin/zonas">
                                    <i class="icon-th-list"></i>
                                    <span class="hidden-tablet">Mantenedor de zonas</span>
                                </a>
                            </li>
                            <li><a  href="/admin/motivos">
                                    <i class="icon-th-list"></i>
                                    <span class="hidden-tablet">Mantenedor de motivos de viaje</span>
                                </a>
                            </li>
                            <li><a  href="/admin/paises">
                                    <i class="icon-th-list"></i>
                                    <span class="hidden-tablet">Mantenedor de paises</span>
                                </a>
                            </li>
                            <li><a  href="/admin/dolar">
                                    <i class="icon-th-list"></i>
                                    <span class="hidden-tablet">Mantenedor de tasa de cambio</span>
                                </a>
                            </li>
                        </ul>
                </div>

                <!-- selector de tema -->
                <div class="btn-group pull-right theme-container" >
                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="icon-tint"></i><span class="hidden-phone">Cambiar diseño</span>
                                <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" id="themes">
                                <li><a data-value="classic" href="#"><i class="icon-blank"></i> Clasico</a></li>
                                <li><a data-value="cerulean" href="#"><i class="icon-blank"></i> Celeste</a></li>
                                <li><a data-value="cyborg" href="#"><i class="icon-blank"></i> Oscuro</a></li>
                                <li><a data-value="redy" href="#"><i class="icon-blank"></i> Rojo</a></li>
                                <li><a data-value="journal" href="#"><i class="icon-blank"></i> Diario</a></li>
                                <li><a data-value="simplex" href="#"><i class="icon-blank"></i> Simple</a></li>
                                <li><a data-value="slate" href="#"><i class="icon-blank"></i> Gris</a></li>
                                <li><a data-value="spacelab" href="#"><i class="icon-blank"></i> Estacion</a></li>
                                <li><a data-value="united" href="#"><i class="icon-blank"></i> Naranjo</a></li>
                        </ul>
                </div>
                <!-- selector de tema fin -->

                <!-- caja de usuario logeado -->
                <div class="btn-group pull-right" >
                        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="icon-user"></i><span class="hidden-phone"> Admin </span>
                                <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                                <li><a href="/admin/login/logout">Salir</a></li>
                        </ul>
                </div>
                <!-- caja usuario logeado fin -->

                
        </div>
    </div>
</div>