<?php

/**
 * Shorthill
 *
 * @copyright   Copyright (c) 2013 Shorthill Solutions (http://www.shorthillsolutions.com)
 * @author      Carlos Ayala <carlos.ayala@shorthillsolutions.com>
 */
?>
<!-- left menu starts -->
<div class="span2 main-menu-span" style="display:none">
    <div class="well nav-collapse sidebar-nav">
        <ul class="nav nav-tabs nav-stacked main-menu">
            <li class="nav-header hidden-tablet">Main</li>
            <li>
                <a class="ajax-link" href="/admin/index">
                    <i class="icon-home"> </i>
                    <span class="hidden-tablet">Home</span>
                </a>
            </li>
            <li><a class="ajax-link" href="/admin/entities">
                    <i class="icon-th-list"></i>
                    <span class="hidden-tablet">Ordenes</span>
                </a>
            </li>
            <li><a class="ajax-link" href="/admin/field">
                    <i class="icon-th-list"></i>
                    <span class="hidden-tablet">Proveedores/Planes</span>
                </a>
            </li>
            <li><a class="ajax-link" href="/admin/property-view">
                    <i class="icon-th-list"></i>
                    <span class="hidden-tablet">Property View</span>
                </a>
            </li>
            <li><a class="ajax-link" href="/admin/property-management">
                    <i class="icon-th-list"></i>
                    <span class="hidden-tablet">Property Management</span>
                </a>
            </li>
        </ul>
    </div><!--/.well -->
</div><!--/span-->
<!-- left menu ends -->
<noscript>
    <div class="alert alert-block span10">
            <h4 class="alert-heading">Warning!</h4>
            <p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
    </div>
</noscript>