<div class="row">
    <div class="col-lg-12">
        <div class="page-title">
            <h1>Image Gallery
                <small>Management</small>
            </h1>
            <ol class="breadcrumb">
                <li><i class="fa fa-dashboard"></i> <a href="/default"> Dashboard </a></li>
                <li class="active">Image Gallery</li>
            </ol>
        </div>
    </div>
</div>

<div class="row">
    <!-- Striped Responsive Table -->
    <div class="col-lg-12">
        <div class="portlet portlet-default">
            <div class="portlet-body">
                <ul class="nav nav-tabs">
                    <li class="active"><a href="#gallery" data-toggle="tab">Gallery</a>
                    </li>
                    <li><a href="#upload" data-toggle="tab">Upload Images</a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade in active" id="gallery">
                        <div class="col-lg-2">
                            <form method="get" action="/imagegallery/index">
                            <div class="input-group">
                                <input id="search" name="search" class="form-control" placeholder="Search..." type="text" value="<?php echo $this->search; ?>">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">Go!</button>
                                </span>
                            </div>
                            </form>
                        </div>
                        <div class="col-lg-12">
                            <div id="wookmark-container" class="row show-grid wookmark-container">
                                <ul id="tiles" class="tiles">
                                    <?php  echo $this->Gallery($this->search); ?>
                                </ul>
                            </div>
                            <?php echo $this->GalleryTotal($this->search); ?>
                        </div>
                    </div>
                    <div class="tab-pane fade " id="upload">
                        <button id="clear-files" class="btn btn-white">Clean completed uploads</button>

                        <br>
                        <br>

                        <form action="/imagegallery/upload/image" enctype="multipart/form-data" class="dropzone" id="my-dropzone">
                            <input type="hidden" name="format" id="format" value="json" />
                        </form>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
</div>