<div class="row">
    <div class="col-lg-12">
        <div class="page-title">
            <h1>Order
                <small>Detail</small>
            </h1>
            <ol class="breadcrumb">
                <li><i class="fa fa-dashboard"></i> <a href="/default"> Dashboard </a></li>
                <li> <a href="/order/index"> Orders </a></li>
                <li> <a href="/order/index/edit/id/<?php echo $this->id_order; ?>"># <?php echo $this->id_order; ?></a></li>
                <li class="active">Detail</li>
            </ol>
        </div>
    </div>
</div>
<div class="row">
    <!-- Striped Responsive Table -->
    <div class="col-lg-12">
        <div class="portlet portlet-default">
            <div class="portlet-heading">
                <div class="portlet-title">
                    <h4>Detail</h4>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="portlet-body">
                <?php echo $this->form; ?>
            </div>
        </div>
        <!-- /.portlet -->
    </div>
    
</div>
