<?php

/**
 * Shorthill
 *
 * @copyright   Copyright (c) 2011 Shorthill Solutions (http://www.shorthillsolutions.com)
 * @author      Carlos Ayala <carlos.ayala@shorthillsolutions.com>
 */
?>


<div id="content" class="span11">
    <!-- El contenido comienza -->
    <div>
        <ul class="breadcrumb">
                <li>
                        <a href="/admin/index">Home</a> 
                        <span class="divider">/</span>
                </li>
                <li>
                        <a href="/admin/zonas/">Zonas</a>
                        <span class="divider">/</span>
                </li>
                <li>
                        <a href="#">Nuevo</a>
                </li>
        </ul>
    </div>

    <div class="row-fluid">
        <div class="box span12">
            <div class="box-header well">
                <h2><i class="icon-info-sign"></i> Zona </h2>
                <div class="box-icon"> 
                  <a title="Ir atras" data-rel="tooltip" href="/admin/zonas/" data-rel="tooltip" class="btn btn-round">
                      <i class="icon-arrow-left"></i>
                  </a> 
                </div>
            </div>
            <div class="box-content">
                <?php echo $this->form; ?>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>

      
<!-- content ends -->
</div><!--/#content.span10-->