<div class="row">
    <div class="col-lg-12">
        <div class="page-title">
            <h1>Order
                <small>Management</small>
            </h1>
            <ol class="breadcrumb">
                <li><i class="fa fa-dashboard"></i> <a href="/default"> Dashboard </a></li>
                <li> <a href="/order/index"> Orders </a></li>
                <li class="active"># <?php echo $this->id_order; ?></li>
            </ol>
        </div>
    </div>
</div>

<input type="hidden" name="id_order" id="id_order" value="<?php echo $this->id_order; ?>" />

<div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-12">
        <div class="portlet portlet-default">
            <div class="portlet-body">
                <div class="row">
                    <div class="col-md-6">
                        <img src="/img/flex-admin-logo@1x.png" />
                        <br>
                        <address>
                            <strong>Alphabet Inc.</strong>
                            <br>795 Folsom Ave, Suite 600
                            <br>San Francisco, CA 94107
                            <br>
                            <abbr title="Phone">P:</abbr>(123) 456-7890
                        </address>
                    </div>
                    <div class="col-md-6 invoice-terms">
                        <h3>Order #<?php echo $this->id_order; ?></h3>
                        
                        <p>
                            Status: <?php echo $this->SelectStatus($this->id_order); ?>
                            <br>
                            Order Date: <?php echo $this->order_date; ?>
                            <br>
                            <!--<strong><span class="text-red">Payment Due: 2/3/14</span></strong>-->
                        </p>
                    </div>
                </div>
                <!-- /.row -->
                <hr>
                <div class="row">
                    <div class="col-md-4">
                        <?php echo $this->BoxBill($this->id_order); ?>
                    </div>
                    <div class="col-md-3">
                        <?php echo $this->BoxShip($this->id_order); ?>
                    </div>
                    <div class="col-md-5">
                        <h3>Payment Instructions</h3>
                        <p>
                            Please send a check or money order made out to <strong>Alphabet Inc.</strong> to the P.O. Box listed above or pay online.
                        </p>
                        <a class="btn btn-green" href="#">Pay Online Now</a>
                    </div>
                </div>
                <!-- /.row -->
                <hr>
                <div class="row">
                    <div class="col-lg-12">
                        <h3>Items</h3>
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped table-hover">
                                <thead>
                                    <tr>
                                        <th width="30px">
                                            <a href="/order/detail/new/order/<?php echo $this->id_order; ?>" class="btn btn-xs btn-green">
                                                <i class="fa fa-list"></i>
                                                Add Detail
                                             </a>

                                        </th>
                                        <th>Quantity</th>
                                        <th>Frame</th>
                                        <th>Word</th>
                                        <th>Letters</th>
                                        <th>Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php echo $this->TableDetail($this->id_order); ?>
                                    <?php echo $this->BoxTotal($this->id_order); ?>
                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->
                        <a class="btn btn-green" href="/order/index/pdf/id/<?php echo $this->id_order; ?>"><i class="fa fa-download"></i> Download Order as PDF</a>
                    </div>
                </div>
                <!-- /.row -->
            </div>
        </div>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- /.row -->

