<ul class="nav navbar-right">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <i class="fa fa-user"></i>  <i class="fa fa-caret-down"></i>
        </a>
        <ul class="dropdown-menu dropdown-user">
            <li>
                <a href="profile.html">
                    <i class="fa fa-user"></i> My Profile
                </a>
            </li>
            <li class="divider"></li>
            <li>
                <a href="#">
                    <i class="fa fa-gear"></i> Settings
                </a>
            </li>
            <li>
                <a class="logout_open" href="#logout">
                    <i class="fa fa-sign-out"></i> Logout
                    <strong>John Smith</strong>
                </a>
            </li>
        </ul>
    </li>
</ul>


