<?php

/**
 * Shorthill
 *
 * @copyright   Copyright (c) 2013 Shorthill Solutions (http://www.shorthillsolutions.com)
 * @author      Carlos Ayala <carlos.ayala@shorthillsolutions.com>
 */
?>
<?php echo $this->doctype(); ?>
<html>
<head>
    <link id="bs-css" href="/admin/css/bootstrap-cerulean.css" rel="stylesheet">
    <style type="text/css">
      body {
            padding-bottom: 40px;
      }
      .sidebar-nav {
            padding: 9px 0;
      }
    </style>
    <?php
        
        echo $this->headStyle();
        echo $this->headLink();
        echo $this->headMeta();
        echo $this->headTitle();
    ?>
    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="/admin/img/favicon.ico">
</head>
<body>
    <?php echo $this->Layout_Header(); ?>
    
    <div class="container-fluid">
        <div class="row-fluid">
            <?php echo $this->Layout_Menu(); ?>
            <?php echo $this->layout()->content; ?>
        </div>
        <?php echo $this->Layout_Footer(); ?>
    </div>
    
    
    <?php
        echo $this->headScript();
    ?>
</body>
</html>