<?php

/**
 * Shorthill
 *
 * @copyright   Copyright (c) 2011 Shorthill Solutions (http://www.shorthillsolutions.com)
 * @author      Carlos Ayala <carlos.ayala@shorthillsolutions.com>
 */
?>
<div class="row-fluid">
    <div class="box span4">
        <div class="box-header well" data-original-title="">
            <h2>
                <i class="icon-th"></i>
                Datos del producto
            </h2>
        </div>
        <div class="box-content">
            <div class="row-fluid">
                <div style="width: 100%">
                    <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>ID :</strong> </div>
                    <div style="width:50%; float:left"> <?php echo $this->id;?></div>
                </div>
                <div class="clear"> </div>
                <div style="width: 100%">
                    <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Plan :</strong> </div>
                    <div style="width:50%; float:left"> <?php echo $this->plan;?></div>
                </div>
                <div class="clear"> </div>
                <div style="width: 100%">
                    <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Proveedor :</strong> </div>
                    <div style="width:50%; float:left"> <?php echo $this->proveedor;?></div>
                </div>
                <div class="clear"> </div>
                <div style="width: 100%">
                    <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Fecha de Emisi&oacute;n :</strong> </div>
                    <div style="width:50%; float:left"> <?php echo $this->fecha_orden;?></div>
                </div>
                <div class="clear"> </div>
                <div style="width: 100%">
                    <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Status :</strong> </div>
                    <div style="width:50%; float:left"> <?php echo $this->status_orden;?></div>
                </div>
                <div class="clear"> </div>
                <div style="width: 100%">
                    <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Tipo descuento :</strong> </div>
                    <div style="width:50%; float:left"> <?php echo $this->tipo_descuento;?></div>
                </div>
                <div class="clear"> </div>
            </div>
        </div>
    </div>

    <div class="box span4">
        <div class="box-header well" data-original-title="">
            <h2>
                <i class="icon-th"></i>
                Datos del viaje
            </h2>
        </div>
        <div class="box-content">
            <div class="row-fluid">
                <div style="width: 100%">
                    <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Fecha Salida :</strong> </div>
                    <div style="width:50%; float:left"> <?php echo $this->fecha_salida;?> </div>
                </div>
                <div class="clear"> </div>
                <div style="width: 100%">
                    <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Fecha Regreso :</strong> </div>
                    <div style="width:50%; float:left"> <?php echo $this->fecha_regreso;?></div>
                </div>
                <div class="clear"> </div>
                <div style="width: 100%">
                    <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Destinos: </strong> </div>
                    <div style="width:50%; float:left"> <?php echo $this->destino;?></div>
                </div>
                <div class="clear"> </div>
            </div>
        </div>
    </div>

    <div class="box span4">
        <div class="box-header well" data-original-title="">
            <h2>
                <i class="icon-th"></i>
                Totales
            </h2>
        </div>
        <div class="box-content">
            <div class="row-fluid">
                <div style="width: 100%">
                    <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Subtotal : </strong> </div>
                    <div style="width:30%; float:left; text-align:right"> <?php echo $this->subtotal;?> </div>
                </div>
                <div class="clear"> </div>
                <div style="width: 100%">
                    <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Descuento :</strong> </div>
                    <div style="width:30%; float:left; text-align:right"> <?php echo $this->descuento;?></div>
                </div>
                <div class="clear"> </div>
                <div style="width: 100%">
                    <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Total :</strong> </div>
                    <div style="width:30%; float:left; text-align:right"><h4> <?php echo $this->total;?> </h4></div>
                </div>
                <div class="clearfix">&nbsp;</div>
                <div class="clearfix">&nbsp;</div>
                <div style="width: 100%">
                    <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Monto Pagado :</strong> </div>
                    <div style="width:30%; float:left; text-align:right"> <?php echo $this->pago;?></div>
                </div>
                <div class="clear"> </div>
                <div style="width: 100%">
                    <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Fecha Pago :</strong> </div>
                    <div style="width:30%; float:left; text-align:right"> <?php echo $this->fecha_pago;?></div>
                </div>
                <div class="clear"> </div>
                <div style="width: 100%">
                    <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Forma de Pago :</strong> </div>
                    <div style="width:30%; float:left; text-align:right"> <?php echo $this->metodo_pago;?></div>
                </div>
                <div class="clear"> </div>
            </div>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="box span12">
        <div class="box-header well" data-original-title="">
            <h2>
                <i class="icon-th"></i>
                Datos de los asegurados
            </h2>
        </div>
        <div class="box-content">
            <div class="row-fluid">
                <?php echo $this->Ordenes_Viajeros($this->id); ?>
            </div>
        </div>
    </div>
</div>