<?php

/**
 * Shorthill
 *
 * @copyright   Copyright (c) 2011 Shorthill Solutions (http://www.shorthillsolutions.com)
 * @author      Carlos Ayala <carlos.ayala@shorthillsolutions.com>
 */
?>

<div id="datos_viajeros1" style="display: inline-block; float: left; font-size: 13px; line-height: 25px; width: 350px; height: 150px; margin-top: 15px ">
    <div class="clear"> </div>
    <div style="width: 100%">
        <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>RUT :</strong> </div>
        <div style="width:50%; float:left"> <?php echo $this->rut;?></div>
    </div>
    <div class="clear"> </div>
    <div style="width: 100%">
        <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Nombre Completo :</strong> </div>
        <div style="width:50%; float:left"> <?php echo $this->nombre;?></div>
    </div>
    <div class="clear"> </div>
    <div style="width: 100%">
        <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Fecha de Nacimiento :</strong> </div>
        <div style="width:50%; float:left"> <?php echo $this->fecha_nacimiento;?></div>
    </div>
    <div class="clear"> </div>
    <div style="width: 100%">
        <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Edad :</strong> </div>
        <div style="width:50%; float:left"> <?php echo $this->edad;?></div>
    </div>
    <div class="clear"> </div>
    <div style="width: 100%">
        <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Email :</strong> </div>
        <div style="width:50%; float:left"><a href="mailto:<?php echo $this->email;?>"> <?php echo $this->email;?> </a></div>
    </div>
    <div class="clear"> </div>
</div>
<div id="datos_viajeros2" style="display: inline-block; float: left; font-size: 13px; line-height: 25px; width: 350px; height: 150px; margin-top: 15px  ">
    <div style="width: 100%">
        <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Tel&eacute;fono Fijo :</strong> </div>
        <div style="width:50%; float:left"><?php echo $this->telefono;?></div>
    </div>
    <div class="clear"> </div>
    <div style="width: 100%">
        <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Direcci&oacute;n :</strong> </div>
        <div style="width:50%; float:left"> <?php echo $this->direccion;?> </div>
    </div>
    <div class="clear"> </div>
    <div style="width: 100%">
        <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Ciudad :</strong> </div>
        <div style="width:50%; float:left"> <?php echo $this->ciudad;?> </div>
    </div>
    <div class="clear"> </div>
    <div style="width: 100%">
        <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Comuna :</strong> </div>
        <div style="width:50%; float:left"> <?php echo $this->comuna;?> </div>
    </div>
    <div class="clear"> </div>

</div>
<div id="datos_viajeros3" style="padding-left: 50px; display: inline-block; float: left; font-size: 13px; line-height: 25px; width: 300px; height: 150px; margin-top: 15px  ">
    <h5>Contacto de Emergencia</h5>
    <div style="width: 100%">
        <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Nombre Completo :</strong> </div>
        <div style="width:50%; float:left"> <?php echo $this->emergencia_nombre;?> </div>
    </div>
    <div class="clear"> </div>
    <div style="width: 100%">
        <div style="width:45%; text-align: right; float:left; padding-right: 10px"><strong>Telefono :</strong> </div>
        <div style="width:50%; float:left"> <?php echo $this->emergencia_telefono;?> </div>
    </div>
    <div class="clear"> </div>
</div>