<?php

/**
 * Shorthill
 *
 * @copyright   Copyright (c) 2011 Shorthill Solutions (http://www.shorthillsolutions.com)
 * @author      Carlos Ayala <carlos.ayala@shorthillsolutions.com>
 */
?>

		
<p class="error-code">
        Error
</p>
<p class="not-found"><?php echo $this->message ?></p>
<div class="clear"></div>
<div class="content">
    <h3>Exception information:</h3>
    <p>
        <b>Message:</b> <?php echo $this->exception->getMessage() ?>
    </p>

    <?php if (isset($this->exception)): ?>
    <h3>Stack trace:</h3>
    <pre><?php echo $this->exception->getTraceAsString() ?>
    </pre>

    <h3>Request Parameters:</h3>
    <pre><?php echo var_export($this->request->getParams(), true) ?>
    </pre>
    <?php endif ?>
    <br/>
    <a href="/">Go Home</a>
</div>
