
    <div class="row">
	<div class="span12">	
            <br /><br /><h1>Galeria de imagenes</h1><br />
	</div>	
	
	<div class="span12">
            <div class="row">
                <div class="span6 offset3">
                    <ul class="nav nav-pills gallery-pills" id="gallery_links">
                        <li><a href="#all" data-id="all">Todas</a></li>
                        <li><a href="#resort" data-id="resort">Las Cabañas</a></li>
                        <li><a href="#rooms" data-id="rooms">Isla de Pascua</a></li>

                    </ul>	
                </div>
            </div>
	</div>
	
	<div class="span12">	
            <ul class="thumbnails" id="gallery">
                <li class="span4 aa-resort" data-id="resort0" data-type="resort">
                        <a href="#" class="thumbnail">
                                <img src="css/images/gallery/resort_1.jpg" alt="">
                        </a>
                </li>
                <li class="span4 aa-resort" data-id="resort1" data-type="resort">
                        <a href="#" class="thumbnail">
                                <img src="css/images/gallery/resort_2.jpg" alt="">
                        </a>
                </li>
                <li class="span4 aa-resort" data-id="resort2" data-type="resort">
                        <a href="#" class="thumbnail">
                                <img src="css/images/gallery/resort_3.jpg" alt="">
                        </a>
                </li>
                <li class="span4 aa-resort" data-id="resort3" data-type="resort">
                        <a href="#" class="thumbnail">
                                <img src="css/images/gallery/resort_4.jpg" alt="">
                        </a>
                </li>
                <li class="span4 aa-resort" data-id="resort4" data-type="resort">
                        <a href="#" class="thumbnail">
                                <img src="css/images/gallery/resort_5.jpg" alt="">
                        </a>
                </li>
                <li class="span4 aa-resort" data-id="resort5" data-type="resort">
                        <a href="#" class="thumbnail">
                                <img src="css/images/gallery/resort_6.jpg" alt="">
                        </a>
                </li>
                <li class="span4 aa-resort" data-id="resort6" data-type="resort">
                        <a href="#" class="thumbnail">
                                <img src="css/images/gallery/resort_7.jpg" alt="">
                        </a>
                </li>
                <li class="span4 aa-resort" data-id="resort7" data-type="resort">
                        <a href="#" class="thumbnail">
                                <img src="css/images/gallery/resort_8.jpg" alt="">
                        </a>
                </li>
                <li class="span4 aa-rooms" data-id="rooms0" data-type="rooms">
                        <a href="#" class="thumbnail">
                                <img src="css/images/gallery/rooms_1.jpg" alt="">
                        </a>
                </li>
                                                <li class="span4 aa-rooms" data-id="rooms1" data-type="rooms">
                        <a href="#" class="thumbnail">
                                <img src="css/images/gallery/rooms_2.jpg" alt="">
                        </a>
                </li>
                                                <li class="span4 aa-rooms" data-id="rooms2" data-type="rooms">
                        <a href="#" class="thumbnail">
                                <img src="css/images/gallery/rooms_3.jpg" alt="">
                        </a>
                </li>
                                                <li class="span4 aa-rooms" data-id="rooms3" data-type="rooms">
                        <a href="#" class="thumbnail">
                                <img src="css/images/gallery/rooms_4.jpg" alt="">
                        </a>
                </li>
                                                <li class="span4 aa-rooms" data-id="rooms4" data-type="rooms">
                        <a href="#" class="thumbnail">
                                <img src="css/images/gallery/rooms_5.jpg" alt="">
                        </a>
                </li>

            </ul>
	</div>

</div>