
    <div class="row">
	
	<div class="span12">	
		<br /><br />
		<h1>Cabañas</h1>

		<div class="row">
			
		
			<div class="span6">
				<h3><span> Maicka 1 </span></h3>
				<a href="general.html"><img src="/img/demo/swimming_pool.jpg" alt="" /></a>
                                <ul class="thumbnails hotel-options no_margin_left">
					<li class="no_margin_left">
                                            <a class="btn btn-large btn-info" href="book-start.html">
                                                <img src="/img/iconos/Wireless.png" alt="" width="24" height="24"  />
                                            </a></li>
					<li><a class="btn btn-large btn-info" href="book-start.html"><img src="/img/iconos/Restaurant-black.png" alt="" width="24"/></a></li>
					<li><a class="btn btn-large btn-info" href="book-start.html"><img src="/img/iconos/Tv-black.png" alt="" width="24"/></a></li>
					<li><a class="btn btn-large btn-info" href="book-start.html"><img src="/img/iconos/Shower.png" alt="" width="24"/></a></li>
				</ul>
				<p> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui. </p>
                                <div class="row center">
					<a class="btn btn-primary btn-large check-availability" href="book-start.html">Ver mas</a>
				</div>
                        </div>				
			<div class="span6">
				<h3><span> Maika 2 </span></h3>
				<a href="general.html"><img src="/img/demo/swimming_pool.jpg" alt="" /></a>
                                <ul class="thumbnails hotel-options no_margin_left">
					<li class="no_margin_left">
                                            <a class="btn btn-large btn-info" href="book-start.html">
                                                <img src="/img/iconos/Wireless.png" alt="" width="24" height="24"  />
                                            </a></li>
					<li><a class="btn btn-large btn-info" href="book-start.html"><img src="/img/iconos/Restaurant-black.png" alt="" width="24"/></a></li>
					<li><a class="btn btn-large btn-info" href="book-start.html"><img src="/img/iconos/Tv-black.png" alt="" width="24"/></a></li>
					<li><a class="btn btn-large btn-info" href="book-start.html"><img src="/img/iconos/Shower.png" alt="" width="24"/></a></li>
				</ul>
				<p> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui. </p>
                                <div class="row center">
					<a class="btn btn-primary btn-large check-availability" href="book-start.html">Ver mas</a>
				</div>
                        </div>	
		
			
		</div>
		


		
	</div>
	
</div>

