
    <div class="row-fluid">
	
	<div class="span12">	
		<br /><br />
		<h1>Cabañas</h1>
		
		<div class="row-fluid">
			
			
			
			<div class="span4">
				<h3>Cabaña <span>Maicka 1</span></h3>
				<a href="book-start.html"><img src="/img/demo/private_villa.jpg" alt="" /></a>
				<ul class="thumbnails hotel-options no_margin_left">
					<li class="no_margin_left">
                                            <a class="btn btn-large btn-info" href="book-start.html">
                                                <img src="/img/iconos/Wireless.png" alt="" width="24" height="24"  />
                                            </a></li>
					<li><a class="btn btn-large btn-info" href="book-start.html"><img src="/img/iconos/Restaurant-black.png" alt="" width="24"/></a></li>
					<li><a class="btn btn-large btn-info" href="book-start.html"><img src="/img/iconos/Tv-black.png" alt="" width="24"/></a></li>
					<li><a class="btn btn-large btn-info" href="book-start.html"><img src="/img/iconos/Shower.png" alt="" width="24"/></a></li>
				</ul>
				<p>Choose a Water Villa and enjoy sublime views of the sea. Enjoy the en-suite bathroom with its own sundeck, gazebo and rain showers. Maximum occupancy 5 adults.</p>

				<div class="row center">
					<a class="btn btn-primary btn-large check-availability" href="book-start.html">Ver mas</a>
				</div>
				
			</div>	
                    
                        <div class="span4">
				<h3>Cabaña <span>Maicka 2</span></h3>
				<a href="book-start.html"><img src="/img/demo/private_villa.jpg" alt="" /></a>
				<ul class="thumbnails hotel-options no_margin_left">
					<li class="no_margin_left">
                                            <a class="btn btn-large btn-info" href="book-start.html">
                                                <img src="/img/iconos/Wireless.png" alt="" width="24" height="24"  />
                                            </a>
                                        </li>
					<li><a class="btn btn-large btn-info" href="book-start.html"><img src="/img/iconos/Restaurant-black.png" alt="" width="24"/></a></li>
					<li><a class="btn btn-large btn-info" href="book-start.html"><img src="/img/iconos/Tv-black.png" alt="" width="24"/></a></li>
					<li><a class="btn btn-large btn-info" href="book-start.html"><img src="/img/iconos/Shower.png" alt="" width="24"/></a></li>
				</ul>
				<p>Choose a Water Villa and enjoy sublime views of the sea. Enjoy the en-suite bathroom with its own sundeck, gazebo and rain showers. Maximum occupancy 5 adults.</p>

				<div class="row center">
					<a class="btn btn-primary btn-large check-availability" href="book-start.html">Ver mas</a>
				</div>
				
			</div>	
			
		</div>
		
		
		
		
	</div>
	
</div>

