<?php

/**
 * Shorthill
 *
 * @copyright   Copyright (c) 2013 Shorthill Solutions (http://www.shorthillsolutions.com)
 * @author      Carlos Ayala <carlos.ayala@shorthillsolutions.com>
 */
?>
<?php echo $this->doctype(); ?>
<html>
<head>
    <?php
        echo $this->headStyle();
        echo $this->headLink();
        echo $this->headMeta();
        echo $this->headTitle();
    ?>
    <link rel="shortcut icon" href="img/favicon.ico">
</head>
<body>
    <?php echo $this->layout()->content; ?>

    <?php
        echo $this->headScript();
    ?>
</body>
</html>