<?php

/**
 * Shorthill
 *
 * @copyright   Copyright (c) 2011 Shorthill Solutions (http://www.shorthillsolutions.com)
 * @author      Carlos Ayala <carlos.ayala@shorthillsolutions.com>
 */
?>


<div id="content" class="span11">
    <!-- El contenido comienza -->
    <div>
        <ul class="breadcrumb">
            <li>
                <a href="/admin/index">Home</a> <span class="divider">/</span>
            </li>
            <li>
                <a href="/admin/property-view">Property View : <strong> <?php echo $this->property_type_name ?> </strong> </a> <span class="divider">/</span>
            </li>
            <li>
                <a href="/admin/data-section/index/property_type/<?php echo $this->id_property_type ?>">Data Section : <strong> <?php echo $this->data_section_name ?></a> </strong> <span class="divider">/</span>
            </li>
            <li>
                <a href="<?php echo $this->redirect_url; ?>">Data Section Fields</a> <span class="divider">/</span>
            </li>
            <li>
                <a href="#">New</a>
            </li>
        </ul>
    </div>

    <div class="row-fluid">
        <div class="box span12">
            <div class="box-header well">
                <h2><i class="icon-info-sign"></i> Data Section Field</h2>
                <div class="box-icon"> 
                  <a title="Go Back" data-rel="tooltip" href="<?php echo $this->redirect_url; ?>" data-rel="tooltip" class="btn btn-round">
                      <i class="icon-arrow-left"></i>
                  </a> 
                </div>
            </div>
            <div class="box-content">
                <?php echo $this->form; ?>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>

      
<!-- content ends -->
</div><!--/#content.span10-->