

<div class="row-fluid slideshow-row">
	
	<div class="span12 slideshow">
		<div class="slider-wrapper theme-default">
			<div class="ribbon"></div>
			<div id="nivoslider-125" class="nivoSlider">
				<img src="/img/demo/slide-1.png" alt="" />
				<img src="/img/demo/slide-2.png" alt="" />
				<img src="/img/demo/slide-3.png" alt="" />
			</div>
		</div>
		<div id="nivoslider-125-caption-0" class="nivo-html-caption">You can add captions too&#8230;</div>
	</div>
	
</div>
<div class="row-fluid home">
	<div class="span12">
		<h2>Bienvenido a <span>Cabañas Maicka</span><br > en el centro del pueblo Hanga Roa </h2>
	</div>
</div>

<hr />
<div class="row-fluid">
	
	<div class="span3">
		<h3><span>C</span>abañas</h3>
		<a href="rooms.html"><img src="/img/cabana/3.jpg" alt="" /></a>
		<p>Completamente equipadas con todo lo que necesita para pasar unas hermosas vacaciones</p>
	</div>		
	<div class="span3">
		<h3><span>Q</span>uienes somos</h3>
		<a href="facilities.html"><img src="/img/demo/services.png" alt="" /></a>
		<p>Cabañas Maicka es atendida por sus propios dueños, quienes le brindan toda la atención necesaria para hacer de su estadia un viaje inolvidable.</p>
	</div>
        <div class="span3">
		<h3><span>U</span>bicacion</h3>
		<a href="map.html"><img src="/img/demo/location.jpg" alt="" /></a>
		<p>Ubicacion privilegiada en el centro del pueblo de Hanga Roa en la calle principal llamada ATAMUTENKENA.</p>
	</div>
	<div class="span3">
		<h3><span>I</span>sla de Pascua</h3>
		<a href="promotions.html"><img src="/img/moai/2.jpg" alt="" /></a>
		<p>Conosca nuestra cultura y nuestras principales atracciones</p>
	</div>		
			
</div>		


