<div class="row">
    <div class="col-lg-12">
        <div class="page-title">
            <h1>Category
                <small>Management</small>
            </h1>
            <ol class="breadcrumb">
                <li><i class="fa fa-dashboard"></i> <a href="/default"> Dashboard </a></li>
                <li>Letter</li>
                <li class="active">Category</li>
            </ol>
        </div>
    </div>
</div>

<div class="row">
    <!-- Striped Responsive Table -->
    <div class="col-lg-2">
        <div class="portlet portlet-default">
            <div class="portlet-heading">
                <div class="portlet-title">
                    <h5><i class="fa fa-search"></i> Search</h5>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="portlet-body">
                <?php echo $this->form; ?>
            </div>
        </div>
        <!-- /.portlet -->
    </div>
    <!-- /.col-lg-6 -->
    
    <div class="col-lg-10">
        <div class="portlet portlet-default">
            <div class="portlet-heading">
                <div class="portlet-title">
                    <h5><i class="fa fa-bars"></i> List</h5>
                </div>
                <div class="portlet-widgets">
                    <a href="/letterart/category/new" class="btn btn-xs btn-green">
                        <i class="fa fa-file-o"></i>
                        New Category
                     </a>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="portlet-body">
                
                <?php echo $this->ListaCategory(); ?>
                
            </div>
        </div>
        <!-- /.portlet -->
    </div>
    <!-- /.col-lg-6 -->

    

</div>