
<h3>Customer</h3> 

<address>
    <a href="/order/address-bill/edit/id/<?php echo $this->id; ?>/order/<?php echo $this->id_order; ?>"> <i class="fa fa-pencil" title="Edit Customer"></i> </a>
    <br>
    <strong><?php echo $this->name; ?></strong> 
    <br><?php echo $this->address1; ?>
    <br><?php echo $this->address2; ?>
    <br>
    <abbr title="Phone"><i class="fa fa-phone"></i>: <?php echo $this->phone; ?></abbr>
    <br>
    <abbr title="Email">@: <?php echo $this->email; ?></abbr>
</address>

