<tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td class="text-right"><strong>Net:</strong>
    </td>
    <td class="text-right"><strong><?php echo $this->net; ?></strong>
    </td>
</tr>
<tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td class="text-right"><strong>Tax:</strong>
    </td>
    <td class="text-right"><strong><?php echo $this->tax; ?></strong>
    </td>
</tr>
<tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td class="text-right"><strong>Shipping:</strong>
    </td>
    <td class="text-right"><strong><?php echo $this->shipping; ?></strong>
    </td>
</tr>

<tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td class="text-right"><strong>Total:</strong>
    </td>
    <td class="text-right text-blue"><strong><?php echo $this->total; ?></strong>
    </td>
</tr>

