<tr>
    <td>
        
        <a href="/order/detail/edit/id/<?php echo $this->id; ?>/order/<?php echo $this->id_order; ?>" class="btn btn-xs btn-default">
            <i class="fa fa-pencil"></i>
            Edit
         </a>
    </td>
    <td><?php echo $this->qty; ?></td>
    <td><?php echo $this->frame; ?></td>
    <td><?php echo $this->word; ?></td>
    <td><?php echo $this->letter; ?></td>
    <td class="text-right"><?php echo $this->price; ?></td>
</tr>
