<?php

/**
 * Shorthill
 *
 * @copyright   Copyright (c) 2011 Shorthill Solutions (http://www.shorthillsolutions.com)
 * @author      Carlos Ayala <carlos.ayala@shorthillsolutions.com>
 */
?>
<div id="content" class="span11">
    <!-- El contenido comienza -->
    <div>
        <ul class="breadcrumb">
            <li>
                <a href="/admin/index">Home</a> <span class="divider">/</span>
            </li>
            <li>
                <a href="#">Ordenes</a>
            </li>
        </ul>
    </div>

    <div class="row-fluid">
        <div class="box span2">
            <div class="box-header well">
                <h2><i class="icon-info-sign"></i> Buscar </h2>             
            </div>
            <div class="box-content">
                <?php echo $this->search_form; ?>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="box span10">
            <div class="box-header well">
                <h2><i class="icon-info-sign"></i> Lista de ordenes </h2>             
            </div>
            <div class="box-content">
                <?php echo $this->Ordenes_List(); ?>
                <div class="clearfix"></div>
            </div>
        </div>
    </div> 
</div>