<div class="block clearfix">
    <div class="row">
        <div class="col-md-2">
            <div role="navigation">
                <ul class="nav nav-default navbar-nav navbar-brand navbar-nav-footer">
                    <span>
                    <li><a href="/">Home</a></li>
                    <li><a href="/about">About Us</a></li>
                    <li><a href="/">Create a Word</a></li>                
                    <li><a href="/products">Products</a></li>                           
                    <li><a href="/contact">Contact</a></li>
                    </span>
                </ul>
            </div>
        
        </div>
        
        <div class="col-md-2">
            <h4>Follow Us</h4>
                <a href="#"><img width="18" src="/img/icons/32x32-pinterest.png" alt="Pinterest" title="Pinterest"></a>
                <a href="#"><img width="18" src="/img/icons/32x32-facebook.png" alt="Facebook" title="Facebook"></a>
                <a href="#"><img width="18" src="/img/icons/32x32-twitter.png" alt="Twitter" title="Twitter"></a>
        </div>
        
        <div class="col-md-4">
            <h4>Contact us</h4>
                <form role="form">
                     <div class="form-group contact-home">
                      <label>NAME</label>
                      <input type="name" class="form-control"  placeholder="Enter Name">
                    </div>
                    <div class="form-group contact-home">
                      <label>EMAIL</label>
                      <input type="email" class="form-control" placeholder="Enter email">
                    </div>
                    <div class="form-group contact-home">
                        <label>MESSAGE</label>
                        <textarea class="form-control" rows="3"></textarea>
                    </div>
                   
                    <button type="submit" class="btn btn-default button-black pull-right">Submit</button>
              </form>

        </div>
        <div class="col-md-4">
            <h4>Map</h4>
            <img src="/img/map.jpg" width="390" height="185" alt="Map" title="Map">
        
        </div>
    </div>
</div>