<div id="container-logo" class="text-center">
    <a href="/"><img src="/img/logo-small-demo.png" alt="Alphabet Photo Pics Logo" width="150" height="69"></a>
    <div class="container-info-header">
        <a href="/cart">Your Shopping Cart</a>&nbsp;&nbsp;<span class="label label-default">&nbsp;&nbsp;</span>
    </div>
</div>
<div id="container-nav"  class="clearfix">
    <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-left">
                <li><a href="/">Home</a></li>
                <li><a href="/about">About Us</a></li>
                <li><a href="/">Create a Word</a></li>                
                <li><a href="/products">Products</a></li>                              
                <li><a href="/contact">Contact</a></li>                
            </ul>
            <ul class="nav navbar-nav navbar-right hidden-sm">
                <li><span>Follow us</span></li>
                <li><a href="#"><img width="18" src="/img/icons/32x32-pinterest.png" alt="Pinterest" title="Pinterest"></a></li>
                <li><a href="#"><img width="18" src="/img/icons/32x32-facebook.png" alt="Facebook" title="Facebook"></a></li>
                <li><a href="#"><img width="18" src="/img/icons/32x32-twitter.png" alt="Twitter" title="Twitter"></a></li>
            </ul>
        </div><!--/.nav-collapse --><!--/.container-fluid -->
    </div>
</div>
