
<div class="row">
    <div class="span12">	
        <br /><br /><h1>Ubicacion y atracciones locales</h1><br />
    </div>
 <div class="span3 sidebar">

  
  <ul class="nav">
    <li><a class="active" href="map.html"><span>Ubicacion</span> cabañas</a></li>
    <li><a href="general.html"><span>Sitios</span> turisticos</a></li>
    <li><a href="general.html"><span>Bares</span> cercanos</a></li>
    <li><a href="general.html"><span>Restoranes</span></a></li>
    <li><a href="typography.html"><span>Como</span> llegar</a></li>
  </ul>	
  <br />

</div>

<div class="span9">	
  <p> Cabañas Maicka se encuentra ubicada en el centro del pueblo de Hanga Roa en la calle principal llamada ATAMUTENKENA, 
      a pasos de la farmacia , feria , rent a car. </p>

  <div id="map_canvas"></div>


  
  
<br /><br />




</div>

</div>