<?php

/**
 * Shorthill
 *
 * @copyright   Copyright (c) 2013 Shorthill Solutions (http://www.shorthillsolutions.com)
 * @author      Carlos Ayala <carlos.ayala@shorthillsolutions.com>
 */
?>
<div id="content" class="span11">
    <!-- El contenido comienza -->
    <div>
        <ul class="breadcrumb">
            <li>
                <a href="/admin/index">Home</a> <span class="divider">/</span>
            </li>
            <li>
                <a href="/admin/paises">Paises</a>
            </li>
        </ul>
    </div>

    <div class="row-fluid">
        <div class="box span2">
            <div class="box-header well">
                <h2><i class="icon-info-sign"></i> Buscar </h2>             
            </div>
            <div class="box-content">
                <?php echo $this->search_form; ?>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="box span10">
            <div class="box-header well">
                <h2><i class="icon-info-sign"></i> Lista de paises </h2>             
            </div>
            <div class="box-content">
                <p>
                    <a class="btn" href="/admin/paises/new">
                        <i class="icon icon-page"></i>Nuevo Pais
                    </a>
                </p>
                <?php echo $this->Pais_Lista(); ?>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>

      
<!-- content ends -->
</div><!--/#content.span10-->

