<?php
/**
 * Shorthill
 *
 * @copyright   Copyright (c) 2011 Shorthill Solutions (http://www.shorthillsolutions.com)
 * @author      Carlos Ayala <carlos.ayala@shorthillsolutions.com>
 */
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link href='http://fonts.googleapis.com/css?family=Creepster|Audiowide' rel='stylesheet' type='text/css'>

        <style>
            *{
                margin:0;
                padding:0;
            }
            body{
                font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
                background-color:#F3FEE5;
                color:#333;
                font-size: 14px;
                padding-bottom:20px;
            }
            .error-code{
                font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
                font-size: 70px;
                color:#333;
                width: 50%;
                /*text-align: right;*/
                /*margin-top: 5%;*/
                text-shadow: 2px 2px 5px hsl(0, 0%, 61%);
                /*float: left;*/
                line-height: 1;
            }
            .not-found{
                width: 47%;
                /*float: right;*/
                /*margin-top: 5%;*/
                font-size: 50px;
                color:#333;
                text-shadow: 2px 2px 5px hsl(0, 0%, 61%);
                /*padding-top: 70px;*/
            }
            .clear{
                float:none;
                clear:both;
            }
            .content{
/*                text-align:left;
                padding-left: 100px;
                line-height: 30px;*/
            }
            input[type=text]{
                border: hsl(247, 89%, 72%) solid 1px;
                outline: none;
                padding: 5px 3px;
                font-size: 16px;
                border-radius: 8px;
            }
            /*			a{
                text-decoration: none;
                color: #9ECDFF;
                text-shadow: 0px 0px 2px white;
               }
               a:hover{
                color:white;
               }*/

        </style>
        <title>Error</title>
    </head>
    <body>

        <p class="error-code">
            Error
        </p>
        <p class="not-found"><?php echo $this->message ?></p>
        <div class="clear"></div>
        <div class="content">
            <h3>Exception information:</h3>
            <p>
                <b>Message:</b> <?php echo $this->exception->getMessage() ?>
            </p>

            <?php if (isset($this->exception)): ?>
                <h3>Stack trace:</h3>
                <pre><?php echo $this->exception->getTraceAsString() ?>
                </pre>

                <h3>Request Parameters:</h3>
                <pre><?php echo var_export($this->request->getParams(), true) ?>
                </pre>
            <?php endif ?>
            <br/>
            <a href="/">Go Home</a>
        </div>
    </body>
</html>